// utils/countries.js — Reusable country list with currency data
// Usage in routes: const { countriesList } = require('../utils/countries');
// Pass to render: res.render('user/register', { countries: countriesList })

const countriesList = [
  { name: "United States",        code: "US", currency: "USD", symbol: "$"  },
  { name: "United Kingdom",       code: "GB", currency: "GBP", symbol: "£"  },
  { name: "Afghanistan",          code: "AF", currency: "AFN", symbol: "؋"  },
  { name: "Albania",              code: "AL", currency: "ALL", symbol: "L"  },
  { name: "Algeria",              code: "DZ", currency: "DZD", symbol: "دج" },
  { name: "American Samoa",       code: "AS", currency: "USD", symbol: "$"  },
  { name: "Andorra",              code: "AD", currency: "EUR", symbol: "€"  },
  { name: "Angola",               code: "AO", currency: "AOA", symbol: "Kz" },
  { name: "Anguilla",             code: "AI", currency: "XCD", symbol: "$"  },
  { name: "Antarctica",           code: "AQ", currency: "",    symbol: ""   },
  { name: "Antigua and Barbuda",  code: "AG", currency: "XCD", symbol: "$"  },
  { name: "Argentina",            code: "AR", currency: "ARS", symbol: "$"  },
  { name: "Armenia",              code: "AM", currency: "AMD", symbol: "֏"  },
  { name: "Aruba",                code: "AW", currency: "AWG", symbol: "ƒ"  },
  { name: "Australia",            code: "AU", currency: "AUD", symbol: "$"  },
  { name: "Austria",              code: "AT", currency: "EUR", symbol: "€"  },
  { name: "Azerbaijan",           code: "AZ", currency: "AZN", symbol: "₼"  },
  { name: "Bahamas",              code: "BS", currency: "BSD", symbol: "$"  },
  { name: "Bahrain",              code: "BH", currency: "BHD", symbol: ".د.ب" },
  { name: "Bangladesh",           code: "BD", currency: "BDT", symbol: "৳"  },
  { name: "Barbados",             code: "BB", currency: "BBD", symbol: "$"  },
  { name: "Belarus",              code: "BY", currency: "BYN", symbol: "Br" },
  { name: "Belgium",              code: "BE", currency: "EUR", symbol: "€"  },
  { name: "Belize",               code: "BZ", currency: "BZD", symbol: "$"  },
  { name: "Benin",                code: "BJ", currency: "XOF", symbol: "Fr" },
  { name: "Bermuda",              code: "BM", currency: "BMD", symbol: "$"  },
  { name: "Bhutan",               code: "BT", currency: "BTN", symbol: "Nu" },
  { name: "Bolivia",              code: "BO", currency: "BOB", symbol: "Bs" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM", symbol: "KM" },
  { name: "Botswana",             code: "BW", currency: "BWP", symbol: "P"  },
  { name: "Brazil",               code: "BR", currency: "BRL", symbol: "R$" },
  { name: "Brunei Darussalam",    code: "BN", currency: "BND", symbol: "$"  },
  { name: "Bulgaria",             code: "BG", currency: "BGN", symbol: "лв" },
  { name: "Burkina Faso",         code: "BF", currency: "XOF", symbol: "Fr" },
  { name: "Burundi",              code: "BI", currency: "BIF", symbol: "Fr" },
  { name: "Cambodia",             code: "KH", currency: "KHR", symbol: "៛"  },
  { name: "Cameroon",             code: "CM", currency: "XAF", symbol: "Fr" },
  { name: "Canada",               code: "CA", currency: "CAD", symbol: "$"  },
  { name: "Cape Verde",           code: "CV", currency: "CVE", symbol: "$"  },
  { name: "Cayman Islands",       code: "KY", currency: "KYD", symbol: "$"  },
  { name: "Central African Republic", code: "CF", currency: "XAF", symbol: "Fr" },
  { name: "Chad",                 code: "TD", currency: "XAF", symbol: "Fr" },
  { name: "Chile",                code: "CL", currency: "CLP", symbol: "$"  },
  { name: "China",                code: "CN", currency: "CNY", symbol: "¥"  },
  { name: "Colombia",             code: "CO", currency: "COP", symbol: "$"  },
  { name: "Comoros",              code: "KM", currency: "KMF", symbol: "Fr" },
  { name: "Congo",                code: "CG", currency: "XAF", symbol: "Fr" },
  { name: "Congo, The Democratic Republic of The", code: "CD", currency: "CDF", symbol: "Fr" },
  { name: "Costa Rica",           code: "CR", currency: "CRC", symbol: "₡"  },
  { name: "Cote D'ivoire",        code: "CI", currency: "XOF", symbol: "Fr" },
  { name: "Croatia",              code: "HR", currency: "EUR", symbol: "€"  },
  { name: "Cuba",                 code: "CU", currency: "CUP", symbol: "$"  },
  { name: "Cyprus",               code: "CY", currency: "EUR", symbol: "€"  },
  { name: "Czech Republic",       code: "CZ", currency: "CZK", symbol: "Kč" },
  { name: "Denmark",              code: "DK", currency: "DKK", symbol: "kr" },
  { name: "Djibouti",             code: "DJ", currency: "DJF", symbol: "Fr" },
  { name: "Dominica",             code: "DM", currency: "XCD", symbol: "$"  },
  { name: "Dominican Republic",   code: "DO", currency: "DOP", symbol: "$"  },
  { name: "Ecuador",              code: "EC", currency: "USD", symbol: "$"  },
  { name: "Egypt",                code: "EG", currency: "EGP", symbol: "£"  },
  { name: "El Salvador",          code: "SV", currency: "USD", symbol: "$"  },
  { name: "Equatorial Guinea",    code: "GQ", currency: "XAF", symbol: "Fr" },
  { name: "Eritrea",              code: "ER", currency: "ERN", symbol: "Nfk"},
  { name: "Estonia",              code: "EE", currency: "EUR", symbol: "€"  },
  { name: "Ethiopia",             code: "ET", currency: "ETB", symbol: "Br" },
  { name: "Fiji",                 code: "FJ", currency: "FJD", symbol: "$"  },
  { name: "Finland",              code: "FI", currency: "EUR", symbol: "€"  },
  { name: "France",               code: "FR", currency: "EUR", symbol: "€"  },
  { name: "Gabon",                code: "GA", currency: "XAF", symbol: "Fr" },
  { name: "Gambia",               code: "GM", currency: "GMD", symbol: "D"  },
  { name: "Georgia",              code: "GE", currency: "GEL", symbol: "₾"  },
  { name: "Germany",              code: "DE", currency: "EUR", symbol: "€"  },
  { name: "Ghana",                code: "GH", currency: "GHS", symbol: "₵"  },
  { name: "Greece",               code: "GR", currency: "EUR", symbol: "€"  },
  { name: "Greenland",            code: "GL", currency: "DKK", symbol: "kr" },
  { name: "Guatemala",            code: "GT", currency: "GTQ", symbol: "Q"  },
  { name: "Guinea",               code: "GN", currency: "GNF", symbol: "Fr" },
  { name: "Guyana",               code: "GY", currency: "GYD", symbol: "$"  },
  { name: "Haiti",                code: "HT", currency: "HTG", symbol: "G"  },
  { name: "Honduras",             code: "HN", currency: "HNL", symbol: "L"  },
  { name: "Hong Kong",            code: "HK", currency: "HKD", symbol: "$"  },
  { name: "Hungary",              code: "HU", currency: "HUF", symbol: "Ft" },
  { name: "Iceland",              code: "IS", currency: "ISK", symbol: "kr" },
  { name: "India",                code: "IN", currency: "INR", symbol: "₹"  },
  { name: "Indonesia",            code: "ID", currency: "IDR", symbol: "Rp" },
  { name: "Iran, Islamic Republic of", code: "IR", currency: "IRR", symbol: "﷼" },
  { name: "Iraq",                 code: "IQ", currency: "IQD", symbol: "ع.د" },
  { name: "Ireland",              code: "IE", currency: "EUR", symbol: "€"  },
  { name: "Israel",               code: "IL", currency: "ILS", symbol: "₪"  },
  { name: "Italy",                code: "IT", currency: "EUR", symbol: "€"  },
  { name: "Jamaica",              code: "JM", currency: "JMD", symbol: "$"  },
  { name: "Japan",                code: "JP", currency: "JPY", symbol: "¥"  },
  { name: "Jordan",               code: "JO", currency: "JOD", symbol: "د.ا" },
  { name: "Kazakhstan",           code: "KZ", currency: "KZT", symbol: "₸"  },
  { name: "Kenya",                code: "KE", currency: "KES", symbol: "Ksh"},
  { name: "Kuwait",               code: "KW", currency: "KWD", symbol: "د.ك" },
  { name: "Latvia",               code: "LV", currency: "EUR", symbol: "€"  },
  { name: "Lebanon",              code: "LB", currency: "LBP", symbol: "ل.ل" },
  { name: "Lesotho",              code: "LS", currency: "LSL", symbol: "L"  },
  { name: "Liberia",              code: "LR", currency: "LRD", symbol: "$"  },
  { name: "Libya",                code: "LY", currency: "LYD", symbol: "ل.د" },
  { name: "Lithuania",            code: "LT", currency: "EUR", symbol: "€"  },
  { name: "Luxembourg",           code: "LU", currency: "EUR", symbol: "€"  },
  { name: "Madagascar",           code: "MG", currency: "MGA", symbol: "Ar" },
  { name: "Malawi",               code: "MW", currency: "MWK", symbol: "MK" },
  { name: "Malaysia",             code: "MY", currency: "MYR", symbol: "RM" },
  { name: "Maldives",             code: "MV", currency: "MVR", symbol: "Rf" },
  { name: "Mali",                 code: "ML", currency: "XOF", symbol: "Fr" },
  { name: "Malta",                code: "MT", currency: "EUR", symbol: "€"  },
  { name: "Mexico",               code: "MX", currency: "MXN", symbol: "$"  },
  { name: "Moldova, Republic of", code: "MD", currency: "MDL", symbol: "L"  },
  { name: "Monaco",               code: "MC", currency: "EUR", symbol: "€"  },
  { name: "Mongolia",             code: "MN", currency: "MNT", symbol: "₮"  },
  { name: "Morocco",              code: "MA", currency: "MAD", symbol: "د.م." },
  { name: "Mozambique",           code: "MZ", currency: "MZN", symbol: "MT" },
  { name: "Myanmar",              code: "MM", currency: "MMK", symbol: "K"  },
  { name: "Namibia",              code: "NA", currency: "NAD", symbol: "$"  },
  { name: "Nepal",                code: "NP", currency: "NPR", symbol: "₨"  },
  { name: "Netherlands",          code: "NL", currency: "EUR", symbol: "€"  },
  { name: "New Zealand",          code: "NZ", currency: "NZD", symbol: "$"  },
  { name: "Nicaragua",            code: "NI", currency: "NIO", symbol: "C$" },
  { name: "Niger",                code: "NE", currency: "XOF", symbol: "Fr" },
  { name: "Nigeria",              code: "NG", currency: "NGN", symbol: "₦"  },
  { name: "Norway",               code: "NO", currency: "NOK", symbol: "kr" },
  { name: "Oman",                 code: "OM", currency: "OMR", symbol: "ر.ع." },
  { name: "Pakistan",             code: "PK", currency: "PKR", symbol: "₨"  },
  { name: "Panama",               code: "PA", currency: "PAB", symbol: "B/." },
  { name: "Papua New Guinea",     code: "PG", currency: "PGK", symbol: "K"  },
  { name: "Paraguay",             code: "PY", currency: "PYG", symbol: "₲"  },
  { name: "Peru",                 code: "PE", currency: "PEN", symbol: "S/." },
  { name: "Philippines",          code: "PH", currency: "PHP", symbol: "₱"  },
  { name: "Poland",               code: "PL", currency: "PLN", symbol: "zł" },
  { name: "Portugal",             code: "PT", currency: "EUR", symbol: "€"  },
  { name: "Qatar",                code: "QA", currency: "QAR", symbol: "ر.ق" },
  { name: "Romania",              code: "RO", currency: "RON", symbol: "lei"},
  { name: "Russian Federation",   code: "RU", currency: "RUB", symbol: "₽"  },
  { name: "Rwanda",               code: "RW", currency: "RWF", symbol: "Fr" },
  { name: "Saudi Arabia",         code: "SA", currency: "SAR", symbol: "ر.س" },
  { name: "Senegal",              code: "SN", currency: "XOF", symbol: "Fr" },
  { name: "Seychelles",           code: "SC", currency: "SCR", symbol: "₨"  },
  { name: "Sierra Leone",         code: "SL", currency: "SLL", symbol: "Le" },
  { name: "Singapore",            code: "SG", currency: "SGD", symbol: "$"  },
  { name: "Slovakia",             code: "SK", currency: "EUR", symbol: "€"  },
  { name: "Slovenia",             code: "SI", currency: "EUR", symbol: "€"  },
  { name: "Somalia",              code: "SO", currency: "SOS", symbol: "Sh" },
  { name: "South Africa",         code: "ZA", currency: "ZAR", symbol: "R"  },
  { name: "Spain",                code: "ES", currency: "EUR", symbol: "€"  },
  { name: "Sri Lanka",            code: "LK", currency: "LKR", symbol: "₨"  },
  { name: "Sudan",                code: "SD", currency: "SDG", symbol: "ج.س." },
  { name: "Suriname",             code: "SR", currency: "SRD", symbol: "$"  },
  { name: "Sweden",               code: "SE", currency: "SEK", symbol: "kr" },
  { name: "Switzerland",          code: "CH", currency: "CHF", symbol: "Fr" },
  { name: "Syrian Arab Republic", code: "SY", currency: "SYP", symbol: "£"  },
  { name: "Taiwan, Province of China", code: "TW", currency: "TWD", symbol: "$" },
  { name: "Tajikistan",           code: "TJ", currency: "TJS", symbol: "SM" },
  { name: "Tanzania, United Republic of", code: "TZ", currency: "TZS", symbol: "Sh" },
  { name: "Thailand",             code: "TH", currency: "THB", symbol: "฿"  },
  { name: "Togo",                 code: "TG", currency: "XOF", symbol: "Fr" },
  { name: "Trinidad and Tobago",  code: "TT", currency: "TTD", symbol: "$"  },
  { name: "Tunisia",              code: "TN", currency: "TND", symbol: "د.ت" },
  { name: "Turkey",               code: "TR", currency: "TRY", symbol: "₺"  },
  { name: "Turkmenistan",         code: "TM", currency: "TMT", symbol: "T"  },
  { name: "Uganda",               code: "UG", currency: "UGX", symbol: "Sh" },
  { name: "Ukraine",              code: "UA", currency: "UAH", symbol: "₴"  },
  { name: "United Arab Emirates", code: "AE", currency: "AED", symbol: "د.إ" },
  { name: "Uruguay",              code: "UY", currency: "UYU", symbol: "$"  },
  { name: "Uzbekistan",           code: "UZ", currency: "UZS", symbol: "лв" },
  { name: "Vanuatu",              code: "VU", currency: "VUV", symbol: "Vt" },
  { name: "Venezuela",            code: "VE", currency: "VES", symbol: "Bs.S" },
  { name: "Viet Nam",             code: "VN", currency: "VND", symbol: "₫"  },
  { name: "Yemen",                code: "YE", currency: "YER", symbol: "﷼"  },
  { name: "Zambia",               code: "ZM", currency: "ZMW", symbol: "ZK" },
  { name: "Zimbabwe",             code: "ZW", currency: "ZWL", symbol: "$"  },
];

/**
 * Build a JSON map { countryName: { currency, symbol } } for client-side lookup.
 * Embed this in your EJS template as a <script> tag so the browser
 * can fill the currency fields without a network round-trip.
 */
const currencyMapJSON = JSON.stringify(
  countriesList.reduce((acc, c) => {
    acc[c.name] = { currency: c.currency, symbol: c.symbol };
    return acc;
  }, {})
);

module.exports = { countriesList, currencyMapJSON };
